# Generated by Django 5.0.6 on 2024-10-15 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_membership_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
