# Generated by Django 5.0.6 on 2024-10-15 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0003_alter_membership_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='is_active',
            new_name='active_association',
        ),
    ]
