# Generated by Django 5.0.6 on 2024-10-15 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0001_initial'),
        ('membership', '0004_rename_is_active_membership_active_association'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='member_associations',
        ),
        migrations.AddField(
            model_name='membership',
            name='member_associations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='association.association'),
        ),
    ]
