# Generated by Django 5.0.6 on 2024-10-17 18:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0001_initial'),
        ('membership', '0005_remove_membership_member_associations_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together={('member', 'member_associations')},
        ),
    ]
