# Generated by Django 5.0.6 on 2024-10-20 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0006_alter_membership_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='has_active_loan',
            field=models.BooleanField(default=False),
        ),
    ]
