# Generated by Django 5.0.6 on 2024-10-22 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0007_membership_has_active_loan'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='national_id_or_passport',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='membership',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
