# Generated by Django 5.0.6 on 2024-10-17 06:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('association', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=9)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('active_status', models.BooleanField(default=False)),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='association.association')),
            ],
            options={
                'unique_together': {('association', 'year')},
            },
        ),
        migrations.CreateModel(
            name='AccountSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('share_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('minimum_deposit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('maximum_deposit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interest_rate', models.DecimalField(decimal_places=2, help_text='Interest rate in percentage', max_digits=5)),
                ('allow_loans', models.BooleanField(default=False)),
                ('deposit_frequency_per_week', models.PositiveIntegerField(default=1, help_text='Number of times deposits can be made per week')),
                ('deposit_day_of_week', models.CharField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], help_text='Specify the day of the week for deposits if applicable', max_length=9, null=True)),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='association.association')),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.financialyear')),
            ],
            options={
                'unique_together': {('association', 'name', 'financial_year')},
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('transaction_type', models.CharField(choices=[('Deposit', 'Deposit'), ('Withdrawal', 'Withdrawal'), ('Loan', 'Loan'), ('Expense', 'Expense')], max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.accountsettings')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
