# Generated by Django 5.0.6 on 2024-10-19 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_accountsettings_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date'], 'verbose_name': 'Transaction', 'verbose_name_plural': 'Transactions'},
        ),
        migrations.AlterUniqueTogether(
            name='accountsettings',
            unique_together={('name', 'financial_year')},
        ),
        migrations.AddField(
            model_name='accountsettings',
            name='eligible_loan_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text=' In percentage', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='accountsettings',
            name='guarantor_balance_must_cover_loan',
            field=models.BooleanField(default=False, help_text='Combined balance of guarantors must cover the loan amount.'),
        ),
        migrations.AddField(
            model_name='accountsettings',
            name='guarantor_must_not_have_loan',
            field=models.BooleanField(default=False, help_text='Guarantor must not have a loan.'),
        ),
        migrations.AddField(
            model_name='accountsettings',
            name='maximum_loan_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='accountsettings',
            name='minimum_loan_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='accountsettings',
            name='require_guarantor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='balance_after_transaction',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Member's balance after this transaction", max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description or notes about the transaction', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='reference',
            field=models.CharField(blank=True, help_text='Unique reference for tracking the transaction', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='shares',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Number of shares involved in the transaction, if applicable', max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('Deposit', 'Deposit'), ('Withdrawal', 'Withdrawal'), ('Loan', 'Loan'), ('Expense', 'Expense'), ('Dividend', 'Dividend'), ('Interest', 'Interest')], max_length=20),
        ),
        migrations.RemoveField(
            model_name='accountsettings',
            name='association',
        ),
    ]
