# Generated by Django 5.0.6 on 2024-10-19 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0001_initial'),
        ('finance', '0003_alter_transaction_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='accountsettings',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='accountsettings',
            name='association',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='association.association'),
        ),
        migrations.AlterUniqueTogether(
            name='accountsettings',
            unique_together={('association', 'name', 'financial_year')},
        ),
    ]
