# Generated by Django 5.0.6 on 2024-10-20 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_alter_accountsettings_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='account_balance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Member's balance after this transaction", max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('Deposit', 'Deposit'), ('Withdrawal', 'Withdrawal'), ('Loan', 'Loan'), ('Expense', 'Expense'), ('Dividend', 'Dividend')], max_length=20),
        ),
    ]
