# Generated by Django 5.0.6 on 2024-10-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_transaction_account_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='account_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Member's balance after this transaction", max_digits=15),
        ),
    ]
