# Generated by Django 5.0.6 on 2024-10-20 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_alter_transaction_account_balance'),
        ('membership', '0006_alter_membership_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='membership.membership'),
        ),
    ]
