# Generated by Django 5.0.6 on 2024-10-20 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_alter_transaction_member'),
        ('membership', '0006_alter_membership_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.accountsettings')),
                ('guarantors', models.ManyToManyField(blank=True, related_name='guaranteed_loans', to='membership.membership')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_requests', to='membership.membership')),
            ],
        ),
    ]
