# Generated by Django 5.0.6 on 2024-10-22 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_loanrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='reference',
            new_name='transaction_id',
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_mode',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Mobile Money', 'Mobile Money'), ('Bank', 'Bank')], default='Cash', max_length=20),
        ),
    ]
