# Generated by Django 5.0.6 on 2024-10-23 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_rename_reference_transaction_transaction_id_and_more'),
        ('membership', '0008_membership_national_id_or_passport_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanrequest',
            name='guarantors',
        ),
        migrations.CreateModel(
            name='Guarantor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes from the guarantor', null=True)),
                ('guarantor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guarantor_for_loans', to='membership.membership')),
                ('loan_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guarantor_requests', to='finance.loanrequest')),
            ],
        ),
    ]
