# Generated by Django 5.0.6 on 2024-10-23 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_notifications_delete_notification'),
        ('membership', '0008_membership_national_id_or_passport_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='association',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='user',
        ),
        migrations.AddField(
            model_name='notifications',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_added', to='membership.membership'),
        ),
        migrations.AddField(
            model_name='notifications',
            name='is_group_notification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notifications',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_received', to='membership.membership'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='action_type',
            field=models.CharField(choices=[('new_loan_request', 'New Loan Request'), ('loan_approved', 'Loan Approved'), ('loan_rejected', 'Loan Rejected'), ('guarantor_added', 'Guarantor Added'), ('guarantor_removed', 'Guarantor Removed'), ('transaction_added', 'Transaction Added')], max_length=50),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
