# Generated by Django 5.0.6 on 2024-10-24 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_notifications_association_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='action_type',
        ),
    ]
